/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthCredentialsDto { 
    username: string;
    password: string;
    role: AuthCredentialsDto.RoleEnum;
}
export namespace AuthCredentialsDto {
    export type RoleEnum = 'admin' | 'banker' | 'punter' | 'supervisor' | 'consortium' | 'carrier';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Banker: 'banker' as RoleEnum,
        Punter: 'punter' as RoleEnum,
        Supervisor: 'supervisor' as RoleEnum,
        Consortium: 'consortium' as RoleEnum,
        Carrier: 'carrier' as RoleEnum
    };
}


