/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankingPercentage } from './bankingPercentage';


export interface BankingDto { 
    _id: object;
    name: string;
    status: boolean;
    ownerUserId: object;
    consortiumId: object;
    ownerUsername: string;
    ownerName: string;
    createdAt: string;
    startOfOperation: string;
    showPercentage: boolean;
    bankingPercentage: Array<BankingPercentage>;
    cancellationTime: number;
    header: string;
    footer: string;
}

