/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Banking { 
    _id: object;
    consortiumId: object;
    startOfOperation: string;
    status: boolean;
    bankingFeeLimits: Array<string>;
    createdAt: string;
}

