/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankingPercentage } from './bankingPercentage';


export interface Banking { 
    _id: object;
    consortiumId: object;
    cancellationTime: number;
    startOfOperation: string;
    status: boolean;
    header: string;
    footer: string;
    bankingPercentage: Array<BankingPercentage>;
}

