/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsortiumDto { 
    ownerName: string;
    ownerUsername: string;
    ownerId: object;
    _id: object;
    name: string;
    createdAt: string;
    status: boolean;
    firstTransactionDate: string;
}

