/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsortiumDto { 
    creationUserId: object;
    modificationUserId: object;
    ownerUserId: object;
    _id: object;
    name: string;
    createdAt: string;
}

