/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Consortium { 
    supervisors: Array<string>;
    consortiumPrefs: object;
    bankings: Array<string>;
    lotteries: Array<string>;
    ownerUserId: object;
    name: string;
    transactions: Array<string>;
    creationUserId: object;
    modificationUserId: object;
    createdAt: string;
    updatedAt: string;
    deletionDate: string;
}

