/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DashboardWebuserDto { 
    _id: object;
    bankingName: string;
    consortiumName: string;
    name: string;
    claimed: number;
    pending: number;
    loser: number;
    total: number;
    profits: number;
    prizes: number;
    pendingPrizes: number;
    balance: number;
}

