/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardDiagramNodeDto } from './dashboardDiagramNodeDto';
import { DashboardDiagramClusterDto } from './dashboardDiagramClusterDto';
import { DashboardDiagramLinkDto } from './dashboardDiagramLinkDto';


export interface DashboardDiagramDto { 
    nodes: Array<DashboardDiagramNodeDto>;
    links: Array<DashboardDiagramLinkDto>;
    clusters: Array<DashboardDiagramClusterDto>;
}

