/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LotteryTime } from './lotteryTime';


export interface Lottery { 
    name: string;
    nickname: string;
    color: string;
    logo: string;
    status: boolean;
    time: LotteryTime;
    bettingLimits: Array<string>;
    prizeLimits: Array<string>;
    bankingFeeLimits: Array<string>;
    fallback: number;
    lastResults: string;
    results: Array<string>;
    creationUserId: string;
    deletionDate: string;
    modificationUserId: string;
}

