/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LotteryTime } from './lotteryTime';
import { Draw } from './draw';


export interface Lottery { 
    _id: object;
    name: string;
    nickname: string;
    color: string;
    logo: string;
    status: boolean;
    time: LotteryTime;
    playTime: string;
    lastDraw: Draw;
    results: Array<string>;
    creationUserId: string;
    deletionDate: string;
    modificationUserId: string;
}

