/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageDto { 
    _id: object;
    originId: object;
    destinationId: object;
    message: string;
    readed: boolean;
    destinationName: string;
    originName: string;
    sender: boolean;
    date: string;
}

