/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Draw } from './draw';
import { Lottery } from './lottery';


export interface ResultDto { 
    lottery: Lottery;
    date: string;
    draw: Draw;
}

