/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayDto } from './playDto';


export interface TicketWebDto { 
    _id: object;
    plays: Array<PlayDto>;
    bankingName: string;
    username: string;
    name: string;
    consortiumName: string;
    betStatus: TicketWebDto.BetStatusEnum;
    date: string;
}
export namespace TicketWebDto {
    export type BetStatusEnum = 'cancelled' | 'claimed' | 'pending' | 'winner' | 'loser' | 'expired';
    export const BetStatusEnum = {
        Cancelled: 'cancelled' as BetStatusEnum,
        Claimed: 'claimed' as BetStatusEnum,
        Pending: 'pending' as BetStatusEnum,
        Winner: 'winner' as BetStatusEnum,
        Loser: 'loser' as BetStatusEnum,
        Expired: 'expired' as BetStatusEnum
    };
}


