/**
 * Betting
 * Betting description
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPreference } from './userPreference';


export interface User { 
    lastLogin: string;
    name: string;
    username: string;
    password: string;
    role: string;
    preferences: UserPreference;
    creationUserId: string;
    deletionDate: string;
    modificationUserId: string;
}

