/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountingDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     */
    accountingControllerGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    accountingControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param accountingDto 
     */
    accountingControllerUpdate(accountingDto: AccountingDto, extraHttpRequestParams?: any): Observable<AccountingDto>;

}
