/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminLotteryReqDto } from '../model/models';
import { AdminLotteryResDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminLotteriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param adminLotteryReqDto 
     */
    adminLotteryControllerCreate(adminLotteryReqDto: AdminLotteryReqDto, extraHttpRequestParams?: any): Observable<AdminLotteryResDto>;

    /**
     * 
     * 
     * @param id 
     */
    adminLotteryControllerDelete(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    adminLotteryControllerGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    adminLotteryControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     * @param value 
     */
    adminLotteryControllerGetFiltered(q: string, value: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param adminLotteryReqDto 
     */
    adminLotteryControllerUpdate(adminLotteryReqDto: AdminLotteryReqDto, extraHttpRequestParams?: any): Observable<AdminLotteryResDto>;

}
