export * from './adminLotteries.service';
import { AdminLotteriesService } from './adminLotteries.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './authPassword.service';
import { AuthPasswordService } from './authPassword.service';
export * from './banking.service';
import { BankingService } from './banking.service';
export * from './bankingLotteries.service';
import { BankingLotteriesService } from './bankingLotteries.service';
export * from './bettingPanel.service';
import { BettingPanelService } from './bettingPanel.service';
export * from './common.service';
import { CommonService } from './common.service';
export * from './consortiumLotteries.service';
import { ConsortiumLotteriesService } from './consortiumLotteries.service';
export * from './consortiums.service';
import { ConsortiumsService } from './consortiums.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './results.service';
import { ResultsService } from './results.service';
export * from './tickets.service';
import { TicketsService } from './tickets.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './webUserLotteries.service';
import { WebUserLotteriesService } from './webUserLotteries.service';
export * from './webusers.service';
import { WebusersService } from './webusers.service';
export const APIS = [AdminLotteriesService, AuthService, AuthPasswordService, BankingService, BankingLotteriesService, BettingPanelService, CommonService, ConsortiumLotteriesService, ConsortiumsService, DashboardService, DefaultService, MessagesService, ResultsService, TicketsService, TransactionsService, UsersService, WebUserLotteriesService, WebusersService];
