/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangeOldPasswordDto } from '../model/models';
import { ChangePasswordDto } from '../model/models';
import { ResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthPasswordServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param changeOldPasswordDto 
     */
    authPasswordControllerChangePassword(changeOldPasswordDto: ChangeOldPasswordDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param changePasswordDto 
     */
    authPasswordControllerChangePasswordFromWindows(changePasswordDto: ChangePasswordDto, extraHttpRequestParams?: any): Observable<{}>;

}
