/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResponseDto } from '../model/models';
import { ResponseSignInDto } from '../model/models';
import { SignInCredentialsDto } from '../model/models';
import { SignUpCredentialsDto } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     */
    authControllerGetLoggedUser(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    authControllerGetToken(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    authControllerLogOut(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param signInCredentialsDto 
     */
    authControllerSingIn(signInCredentialsDto: SignInCredentialsDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param signUpCredentialsDto 
     */
    authControllerSingUp(signUpCredentialsDto: SignUpCredentialsDto, extraHttpRequestParams?: any): Observable<ResponseDto>;

    /**
     * 
     * 
     * @param signUpCredentialsDto 
     */
    authControllerSingUpLogged(signUpCredentialsDto: SignUpCredentialsDto, extraHttpRequestParams?: any): Observable<ResponseDto>;

}
