/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Banking } from '../model/models';
import { BankingDto } from '../model/models';
import { CreateBankingDto } from '../model/models';
import { UpdateBankingDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BankingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param createBankingDto 
     */
    bankingsControllerCreate(createBankingDto: CreateBankingDto, extraHttpRequestParams?: any): Observable<Banking>;

    /**
     * 
     * 
     * @param id 
     */
    bankingsControllerDelete(id: string, extraHttpRequestParams?: any): Observable<Banking>;

    /**
     * 
     * 
     */
    bankingsControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param field 
     */
    bankingsControllerFindOne(field: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    bankingsControllerGetUserBanking(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param updateBankingDto 
     */
    bankingsControllerUpdate(updateBankingDto: UpdateBankingDto, extraHttpRequestParams?: any): Observable<Banking>;

}
