/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BetDto } from '../model/models';
import { ClaimBetDto } from '../model/models';
import { CreateBetDto } from '../model/models';
import { LimitVerifyDto } from '../model/models';
import { ResumeSellsDto } from '../model/models';
import { UpdateBetDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BettingPanelServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param updateBetDto 
     */
    bettingPanelControllerCancelBet(updateBetDto: UpdateBetDto, extraHttpRequestParams?: any): Observable<BetDto>;

    /**
     * 
     * 
     * @param claimBetDto 
     */
    bettingPanelControllerClaimTicket(claimBetDto: ClaimBetDto, extraHttpRequestParams?: any): Observable<BetDto>;

    /**
     * 
     * 
     * @param createBetDto 
     */
    bettingPanelControllerCreate(createBetDto: CreateBetDto, extraHttpRequestParams?: any): Observable<BetDto>;

    /**
     * 
     * 
     * @param createBetDto 
     */
    bettingPanelControllerCreateForWebUser(createBetDto: CreateBetDto, extraHttpRequestParams?: any): Observable<BetDto>;

    /**
     * 
     * 
     * @param id 
     */
    bettingPanelControllerGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    bettingPanelControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param claimBetDto 
     */
    bettingPanelControllerGetClaimTicket(claimBetDto: ClaimBetDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     */
    bettingPanelControllerGetFiltered(q: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    bettingPanelControllerGetResumeSells(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param limitVerifyDto 
     */
    bettingPanelControllerVerifyLimit(limitVerifyDto: LimitVerifyDto, extraHttpRequestParams?: any): Observable<number>;

}
