/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Consortium } from '../model/models';
import { ConsortiumDto } from '../model/models';
import { CreateConsortiumDto } from '../model/models';
import { UpdateConsortiumDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConsortiumsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param createConsortiumDto 
     */
    consortiumControllerCreate(createConsortiumDto: CreateConsortiumDto, extraHttpRequestParams?: any): Observable<Consortium>;

    /**
     * 
     * 
     * @param id 
     */
    consortiumControllerDelete(id: string, extraHttpRequestParams?: any): Observable<Consortium>;

    /**
     * 
     * 
     * @param id 
     */
    consortiumControllerGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    consortiumControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    consortiumControllerGetConsortiumOfUser(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     */
    consortiumControllerGetFiltered(q: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param updateConsortiumDto 
     */
    consortiumControllerUpdate(updateConsortiumDto: UpdateConsortiumDto, extraHttpRequestParams?: any): Observable<Consortium>;

}
