/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConsortiumLotteryDto } from '../model/models';
import { ConsortiumUpdateLotteryDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConsortiumLotteriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param id 
     */
    consortiumLotteryControllerGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    consortiumLotteryControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param consortiumUpdateLotteryDto 
     */
    consortiumLotteryControllerUpdate(consortiumUpdateLotteryDto: ConsortiumUpdateLotteryDto, extraHttpRequestParams?: any): Observable<ConsortiumUpdateLotteryDto>;

}
