/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DashboardBankingDto } from '../model/models';
import { DashboardConsortiumDto } from '../model/models';
import { DashboardDiagramDto } from '../model/models';
import { DashboardGraphBalanceBankingDto } from '../model/models';
import { DashboardGraphBankingDto } from '../model/models';
import { DashboardGraphConsortiumBalanceBankingDto } from '../model/models';
import { DashboardGraphConsortiumDto } from '../model/models';
import { DashboardPlayedNumbersDto } from '../model/models';
import { DashboardWebuserDto } from '../model/models';
import { DashboardWidgetsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     */
    dashboardControllerGetAdminWidgetsStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetBankingPlayedNumbersStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetBankingWidgetsStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetBankingsStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetConsortiumPlayedNumbersStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetConsortiumWidgetsStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetConsortiumsStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetDashboardDiagram(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetGraphBankingBalanceStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetGraphBankingStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetGraphConsortiumBankingBalanceStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetGraphConsortiumStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetWebUserWidgetsStatistics(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    dashboardControllerGetWebUsersStatistics(extraHttpRequestParams?: any): Observable<{}>;

}
