/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param body 
     */
    subscriptionsControllerCreate(body: object, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     * @param value 
     */
    subscriptionsControllerFindAll(q: string, value: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     * @param value 
     */
    subscriptionsControllerFindOne(q: string, value: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    subscriptionsControllerRemove(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    subscriptionsControllerUpdate(body: object, extraHttpRequestParams?: any): Observable<{}>;

}
