/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MessageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MessagesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param body 
     */
    chatControllerCreate(body: object, extraHttpRequestParams?: any): Observable<MessageDto>;

    /**
     * 
     * 
     */
    chatControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    chatControllerGetAllUnreadMessages(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    chatControllerReadMessages(body: object, extraHttpRequestParams?: any): Observable<boolean>;

}
