/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTransactionDto } from '../model/models';
import { PaginationQueryDto } from '../model/models';
import { ResponseQueryDto } from '../model/models';
import { Transaction } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TransactionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param createTransactionDto 
     */
    transactionControllerCreateTransactionAdmin(createTransactionDto: CreateTransactionDto, extraHttpRequestParams?: any): Observable<Transaction>;

    /**
     * 
     * 
     * @param createTransactionDto 
     */
    transactionControllerCreateTransactionBanking(createTransactionDto: CreateTransactionDto, extraHttpRequestParams?: any): Observable<Transaction>;

    /**
     * 
     * 
     * @param createTransactionDto 
     */
    transactionControllerCreateTransactionConsortium(createTransactionDto: CreateTransactionDto, extraHttpRequestParams?: any): Observable<Transaction>;

    /**
     * 
     * 
     * @param id 
     */
    transactionControllerGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param paginationQueryDto 
     */
    transactionControllerGetAll(paginationQueryDto: PaginationQueryDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     */
    transactionControllerGetFiltered(q: string, extraHttpRequestParams?: any): Observable<{}>;

}
