/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';
import { UserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param id 
     */
    usersControllerDelete(id: string, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param id 
     */
    usersControllerGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    usersControllerGetAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param q 
     * @param value 
     */
    usersControllerGetFiltered(q: string, value: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param userDto 
     */
    usersControllerUpdate(userDto: UserDto, extraHttpRequestParams?: any): Observable<User>;

}
