/**
 * Betting
 * Betting for Republic
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateWebUserDto } from '../model/models';
import { UpdateWebUserDto } from '../model/models';
import { WebUser } from '../model/models';
import { WebUserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WebusersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * 
     * 
     * @param createWebUserDto 
     */
    webUsersControllerCreate(createWebUserDto: CreateWebUserDto, extraHttpRequestParams?: any): Observable<WebUser>;

    /**
     * 
     * 
     * @param id 
     */
    webUsersControllerDelete(id: string, extraHttpRequestParams?: any): Observable<WebUser>;

    /**
     * 
     * 
     */
    webUsersControllerFindAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param field 
     */
    webUsersControllerFindOne(field: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param updateWebUserDto 
     */
    webUsersControllerUpdate(updateWebUserDto: UpdateWebUserDto, extraHttpRequestParams?: any): Observable<WebUser>;

}
